app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: bot
  jackson:
    time-zone: UTC


rate-limiting:
  capacity: 100
  tokens-per-period: 100
  gen-period: 1s
  excluded-ips: 127.0.0.1

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui
