app:
  telegram-token: ${TELEGRAM_TOKEN}

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: bot
  jackson:
    time-zone: UTC
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: edu.java.bot.models.ListLinkUpdates
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: localhost:9092
      properties:
        spring.json.add.type.headers: false

retry:
  client-configs:
    - client: scrapper
      mode: fixed
      max-attempts: 10
      min-delay: 1s
      codes: 429



rate-limiting:
  capacity: 100
  tokens-per-period: 100
  gen-period: 1s
  excluded-ips: 127.0.0.1

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
springdoc:
  swagger-ui:
    path: /swagger-ui
