/*
 * This file is generated by jOOQ.
 */

package edu.java.domain.jooq;

import edu.java.domain.jooq.tables.Chat;
import edu.java.domain.jooq.tables.ChatToLink;
import edu.java.domain.jooq.tables.Link;
import edu.java.domain.jooq.tables.records.ChatRecord;
import edu.java.domain.jooq.tables.records.ChatToLinkRecord;
import edu.java.domain.jooq.tables.records.LinkRecord;
import javax.annotation.processing.Generated;
import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChatRecord> CONSTRAINT_1 =
        Internal.createUniqueKey(Chat.CHAT, DSL.name("CONSTRAINT_1"), new TableField[] {Chat.CHAT.CHAT_ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_2 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_2"), new TableField[] {Link.LINK.ID}, true);
    public static final UniqueKey<LinkRecord> CONSTRAINT_23 =
        Internal.createUniqueKey(Link.LINK, DSL.name("CONSTRAINT_23"), new TableField[] {Link.LINK.URL}, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ChatToLinkRecord, ChatRecord> CONSTRAINT_5 =
        Internal.createForeignKey(ChatToLink.CHAT_TO_LINK,
            DSL.name("CONSTRAINT_5"),
            new TableField[] {ChatToLink.CHAT_TO_LINK.CHAT_ID},
            Keys.CONSTRAINT_1,
            new TableField[] {Chat.CHAT.CHAT_ID},
            true
        );
    public static final ForeignKey<ChatToLinkRecord, LinkRecord> CONSTRAINT_53 =
        Internal.createForeignKey(ChatToLink.CHAT_TO_LINK,
            DSL.name("CONSTRAINT_53"),
            new TableField[] {ChatToLink.CHAT_TO_LINK.LINK_ID},
            Keys.CONSTRAINT_2,
            new TableField[] {Link.LINK.ID},
            true
        );
}
